export const EMPTY_STATE_STRUCTURE = [
  { source: 'Mizan (391 Hesap. KDV)', target: 'KDV-1 Beyannamesi', icon: '📋', threshold: '₺100', group: 'beyan' },
  { source: 'Mizan (600-602 Satışlar)', target: 'KDV-1 Matrah', icon: '📊', threshold: '≤%5', group: 'beyan' },
  { source: 'Mizan (360 Stopaj)', target: 'Muhtasar Beyannamesi', icon: '👥', threshold: '≤%10', group: 'beyan' },
  { source: 'Mizan (590/690 Kar)', target: 'Geçici Vergi Beyannamesi', icon: '📈', threshold: '₺100', group: 'beyan' },
  { source: 'Toplam Borç', target: 'Toplam Alacak', icon: '⚖️', threshold: '₺0', group: 'teknik' },
  { source: 'Ters Bakiye Kontrolü', target: 'Tek Düzen Hesap Planı', icon: '🔍', threshold: '0 hesap', group: 'teknik' },
  { source: 'Eksi Hesap Kontrolü', target: 'Kritik Hesaplar', icon: '⚠️', threshold: '0 hesap', group: 'teknik' },
];

export const CROSS_CHECK_SMMM_INFO = {
  title: 'Çapraz Kontrol Matrisi',
  description: 'Mizan, Beyanname ve Teknik Kontrol tutarlılık analizi',
  context: [
    '🔹 GRUP 1 - Mizan vs Beyannameler: KDV-1, Muhtasar, Geçici Vergi, Kurumlar Vergisi karşılaştırması.',
    '🔹 GRUP 2 - Mizan vs Teknik Kontroller: Mizan denklik, ters bakiye, eksi hesap tespiti.',
    '🔹 GRUP 3 - Mizan vs Mali Tablolar: Bilanço ve Gelir Tablosu uyumu (Yakında).',
    '🔹 GRUP 4 - Mizan vs e-Fatura: e-Fatura satış/alış tutarları kontrolü (Yakında).',
    'NOT: Banka mutabakatı ayrı menüde yapılmaktadır.',
    'VDK-RAM sistemi bu çapraz kontrolleri otomatik yaparak risk puanı üretiyor.',
  ],
  farkTipleri: [
    { level: 'Eşleşme', desc: 'Fark yok veya ≤₺100 - Kayıtlar tutarlı', color: 'bg-[#ECFDF5] text-[#00804D]' },
    { level: 'Küçük Fark', desc: '≤%5 fark - Yuvarlama/zamanlama farkı olabilir', color: 'bg-[#FFFBEB] text-[#FA841E]' },
    { level: 'Büyük Fark', desc: '%5-10 fark - İncelenmeli, muhtemel kayıt hatası', color: 'bg-[#FFFBEB] text-[#FA841E]' },
    { level: 'Kritik', desc: '>%10 fark - Acil düzeltme gerekli', color: 'bg-[#FEF2F2] text-[#BF192B]' },
  ],
  actions: [
    'Kritik farkları öncelikli olarak inceleyin',
    'Fark nedenini belirleyin (zamanlama, yuvarlama, hata)',
    'Düzeltme fişlerini hazırlayın',
    'Mutabakat dosyasını arşivleyin',
  ],
};

export const SAHTE_FATURA_RISK_KRITERLERI = {
  VL_MATRAH_TUTARSIZLIK: {
    kod: 'VL-01',
    ad: 'Matrah Değişim Anomalisi',
    aciklama: 'Yıllar arası matrah değişiminin sektör ortalamasından sapması',
    esik_uyari: 30,
    esik_kritik: 50,
    kaynak: 'vergi_levhasi' as const,
    mevzuat: ['VUK 134', 'KVK 6'],
  },
  VL_NACE_UYUMSUZLUK: {
    kod: 'VL-02',
    ad: 'NACE Kodu Uyumsuzluğu',
    aciklama: 'Faaliyet alanı ile alım/satım kalıplarının uyumsuzluğu',
    kaynak: 'vergi_levhasi' as const,
    mevzuat: ['VUK 359', 'VUK 370'],
  },
  TS_YENİ_KURULUŞ: {
    kod: 'TS-01',
    ad: 'Yeni Kuruluş Riski',
    aciklama: 'Son 2 yıl içinde kurulmuş şirketlerden yüksek tutarlı alım',
    esik_kritik: 2,
    kaynak: 'ticaret_sicil' as const,
    mevzuat: ['VUK 359'],
  },
  TS_ADRES_DEGISIKLIGI: {
    kod: 'TS-02',
    ad: 'Sık Adres Değişikliği',
    aciklama: 'Son 1 yılda 2+ adres değişikliği yapan tedarikçi',
    esik_kritik: 2,
    kaynak: 'ticaret_sicil' as const,
  },
  TS_TASFIYE: {
    kod: 'TS-03',
    ad: 'Tasfiye Halindeki Şirket',
    aciklama: 'Tasfiye sürecindeki şirketlerden alım yapılması',
    kaynak: 'ticaret_sicil' as const,
    mevzuat: ['TTK 533', 'VUK 359'],
  },
  TS_SERMAYE_DUSUK: {
    kod: 'TS-04',
    ad: 'Düşük Sermaye / Yüksek Ciro',
    aciklama: 'Sermayesinin 10+ katı ciro yapan şirket',
    esik_kritik: 10,
    kaynak: 'ticaret_sicil' as const,
    mevzuat: ['VDK RAM Kriteri'],
  },
  EF_YILSONU_YOGUNLUK: {
    kod: 'EF-01',
    ad: 'Yıl Sonu Fatura Yoğunluğu',
    aciklama: 'Aralık ayında toplam alımların %40+ oranında olması',
    esik_uyari: 30,
    esik_kritik: 40,
    kaynak: 'e_fatura' as const,
    mevzuat: ['VUK 359', 'VDK RAM'],
  },
  EF_YUVARLAK_TUTAR: {
    kod: 'EF-02',
    ad: 'Yuvarlak Tutar Paterni',
    aciklama: 'Faturaların %50+ oranında yuvarlak tutarlı olması',
    esik_kritik: 50,
    kaynak: 'e_fatura' as const,
  },
  SA_KDV_YUKU_DUSUK: {
    kod: 'SA-01',
    ad: 'Düşük KDV Yükü',
    aciklama: 'KDV yükünün sektör ortalamasının %50 altında olması',
    esik_uyari: 0.3,
    esik_kritik: 0.5,
    kaynak: 'sektor_analizi' as const,
    mevzuat: ['KDVK 29', 'VDK RAM'],
  },
  SA_BRUT_KAR_DUSUK: {
    kod: 'SA-02',
    ad: 'Düşük Brüt Kar Marjı',
    aciklama: 'Brüt kar marjının sektör ortalamasının %50 altında olması',
    esik_kritik: 0.5,
    kaynak: 'sektor_analizi' as const,
    mevzuat: ['VUK 134', 'KVK 6'],
  },
};
