import type { RiskReviewItem, RiskQueueStats } from './types';

export const MOCK_RISK_QUEUE: RiskReviewItem[] = [
  {
    id: 'review-001',
    mukellefId: 'client-001',
    mukellefAdi: 'ÖZKAN KIRTASİYE TİC. LTD. ŞTİ.',
    mukellefVkn: '1234567890',
    sektor: 'Perakende',
    donem: '2025-Q2',
    riskSkoru: 87,
    riskLevel: 'kritik',
    topRiskFactors: [
      { id: 'rf-001', kod: 'K-09', baslik: 'Yüksek Kasa Bakiyesi', aciklama: 'Kasa hesabı aktif toplamın %5 eşiğini aşıyor', multiplier: 4.2, deger: '2.500.000 TL', esik: '%5', birim: 'TL', seviye: 'kritik' },
      { id: 'rf-002', kod: 'K-15', baslik: 'Ortaklara Yüksek Borç', aciklama: 'Ortaklara borç sermayenin 3 katını aşıyor', multiplier: 3.8, deger: '3.200.000 TL', esik: '1.000.000 TL', birim: 'TL', seviye: 'kritik' },
      { id: 'rf-003', kod: 'RAM-03', baslik: 'Benford Analizi Sapması', aciklama: 'Fatura tutarlarında anomali', multiplier: 2.1, deger: '0.042', esik: '0.025', seviye: 'yuksek' },
    ],
    status: 'pending',
    createdAt: '2025-01-07T10:00:00Z',
  },
  {
    id: 'review-002',
    mukellefId: 'client-002',
    mukellefAdi: 'ABC TEKSTİL SAN. VE TİC. A.Ş.',
    mukellefVkn: '9876543210',
    sektor: 'Tekstil',
    donem: '2025-Q2',
    riskSkoru: 82,
    riskLevel: 'kritik',
    topRiskFactors: [
      { id: 'rf-004', kod: 'KURGAN-7', baslik: 'Sahte Fatura Riski', aciklama: '3 tedarikçi VDK kara listesinde', multiplier: 5.5, deger: '3 firma', esik: '0', seviye: 'kritik' },
      { id: 'rf-005', kod: 'K-12', baslik: 'Şüpheli Alacak Oranı', aciklama: 'Şüpheli alacak karşılığı yüksek', multiplier: 2.3, deger: '%18', esik: '%10', seviye: 'yuksek' },
    ],
    status: 'pending',
    createdAt: '2025-01-07T09:30:00Z',
  },
  {
    id: 'review-003',
    mukellefId: 'client-003',
    mukellefAdi: 'XYZ DANIŞMANLIK HİZM. LTD. ŞTİ.',
    sektor: 'Hizmet',
    donem: '2025-Q2',
    riskSkoru: 68,
    riskLevel: 'yuksek',
    topRiskFactors: [
      { id: 'rf-006', kod: 'K-09', baslik: 'Yüksek Kasa Bakiyesi', aciklama: 'Kasa hesabı aktif toplamın %5 eşiğini aşıyor', multiplier: 2.8, deger: '850.000 TL', esik: '%5', birim: 'TL', seviye: 'yuksek' },
    ],
    status: 'investigating',
    assignedTo: 'Ahmet Yılmaz',
    createdAt: '2025-01-06T14:00:00Z',
    updatedAt: '2025-01-07T08:00:00Z',
  },
  {
    id: 'review-004',
    mukellefId: 'client-004',
    mukellefAdi: 'DEF İNŞAAT TAAHHÜT A.Ş.',
    sektor: 'İnşaat',
    donem: '2025-Q2',
    riskSkoru: 65,
    riskLevel: 'yuksek',
    topRiskFactors: [
      { id: 'rf-007', kod: 'RAM-11', baslik: 'Yıllara Yaygın İnşaat Sapması', aciklama: 'Hakediş ve maliyet oranı tutarsız', multiplier: 2.1, deger: '%35', esik: '%20', seviye: 'yuksek' },
    ],
    status: 'pending',
    createdAt: '2025-01-07T08:00:00Z',
  },
  {
    id: 'review-005',
    mukellefId: 'client-005',
    mukellefAdi: 'GHI GIDA ÜRETİM LTD. ŞTİ.',
    sektor: 'Gıda',
    donem: '2025-Q2',
    riskSkoru: 45,
    riskLevel: 'orta',
    topRiskFactors: [
      { id: 'rf-009', kod: 'K-06', baslik: 'Stok Devir Hızı Düşük', aciklama: 'Sektör ortalamasının altında', multiplier: 1.5, deger: '2.3', esik: '4.0', seviye: 'orta' },
    ],
    status: 'approved',
    createdAt: '2025-01-05T12:00:00Z',
    updatedAt: '2025-01-06T16:00:00Z',
  },
  {
    id: 'review-006',
    mukellefId: 'client-006',
    mukellefAdi: 'JKL OTOMOTİV YEDEK PARÇA LTD. ŞTİ.',
    sektor: 'Otomotiv',
    donem: '2025-Q2',
    riskSkoru: 34,
    riskLevel: 'dusuk',
    topRiskFactors: [],
    status: 'approved',
    createdAt: '2025-01-04T10:00:00Z',
  },
];

export const MOCK_QUEUE_STATS: RiskQueueStats = {
  toplam: MOCK_RISK_QUEUE.length,
  kritik: MOCK_RISK_QUEUE.filter(r => r.riskLevel === 'kritik').length,
  yuksek: MOCK_RISK_QUEUE.filter(r => r.riskLevel === 'yuksek').length,
  orta: MOCK_RISK_QUEUE.filter(r => r.riskLevel === 'orta').length,
  dusuk: MOCK_RISK_QUEUE.filter(r => r.riskLevel === 'dusuk').length,
  bekleyen: MOCK_RISK_QUEUE.filter(r => r.status === 'pending').length,
};
