import type { AksiyonItem } from './types';

// Test icin mock aksiyonlar
export const MOCK_AKSIYONLAR: AksiyonItem[] = [
  {
    id: 'aks-001',
    baslik: 'KDV Beyanname Hazirla',
    aciklama: 'Aralik donemi KDV beyannamesi hazirlanmali',
    mukellef: { id: 'muk-001', ad: 'OZKAN_KIRTASIYE' },
    oncelik: 'acil',
    kaynak: 'vergi_takvimi',
    sonTarih: new Date('2026-01-28'),
    kalanGun: 22,
    tahminiDakika: 30,
    aksiyonTipi: 'hazirla',
    aksiyonUrl: '/v2/beyan/kdv',
    aksiyonLabel: 'Beyani Hazirla',
    problemDurumu: 'd2_tanimlandi',
    olusturmaTarihi: new Date(),
  },
  {
    id: 'aks-002',
    baslik: 'Enflasyon Belgesi Yukle',
    aciklama: '3 belge eksik: Duzeltilmis Bilanco, Gelir Tablosu, Ozkaynak',
    detay: 'Enflasyon muhasebesi icin gerekli belgeler eksik',
    mukellef: { id: 'muk-001', ad: 'OZKAN_KIRTASIYE' },
    oncelik: 'acil',
    kaynak: 'eksik_belge',
    sonTarih: new Date('2026-01-09'),
    kalanGun: 3,
    tahminiDakika: 15,
    aksiyonTipi: 'yukle',
    aksiyonUrl: '/v2/upload?tip=enflasyon',
    aksiyonLabel: 'Belgeleri Yukle',
    problemDurumu: 'd1_ekip',
    olusturmaTarihi: new Date(),
  },
  {
    id: 'aks-003',
    baslik: 'VDK Risk Incele: K-09 Yuksek Kasa',
    aciklama: 'Kasa bakiyesi esik degerin 3x uzerinde',
    detay: 'Kasa: 2,500,000 TL (Aktif %15)',
    mukellef: { id: 'muk-001', ad: 'OZKAN_KIRTASIYE' },
    oncelik: 'normal',
    kaynak: 'vdk_risk',
    tahminiDakika: 20,
    aksiyonTipi: 'incele',
    aksiyonUrl: '/v2/vdk/K-09',
    aksiyonLabel: 'Detay Incele',
    problemDurumu: 'd0_farkedildi',
    iliskiliVeri: {
      tip: 'vdk_kriter',
      id: 'K-09',
      ekBilgi: { skor: 72, esik: 500000, gerceklesen: 2500000 },
    },
    tekrarSayisi: 3,
    olusturmaTarihi: new Date(),
  },
  {
    id: 'aks-004',
    baslik: 'Tedarikci Mutabakat Kontrolu',
    aciklama: 'E-fatura kayitlari ile muhasebe kayitlari arasinda uyumsuzluk',
    detay: '125,000 TL fark tespit edildi',
    mukellef: { id: 'muk-001', ad: 'OZKAN_KIRTASIYE' },
    oncelik: 'normal',
    kaynak: 'mutabakat',
    tahminiDakika: 25,
    aksiyonTipi: 'incele',
    aksiyonUrl: '/v2/mutabakat/tedarikci',
    aksiyonLabel: 'Mutabakati Incele',
    problemDurumu: 'd3_gecici',
    olusturmaTarihi: new Date(),
  },
  {
    id: 'aks-005',
    baslik: 'Yeni Mevzuat: KDV Tebligi Degisikligi',
    aciklama: 'Iade sureleri degisti, bu mukellefi etkileyebilir',
    oncelik: 'bilgi',
    kaynak: 'regwatch',
    tahminiDakika: 5,
    aksiyonTipi: 'oku',
    aksiyonUrl: '/v2/regwatch/teblig-123',
    aksiyonLabel: 'Oku ve Isaretle',
    olusturmaTarihi: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 gun once
  },
];
